from EllipticCurve.S256Point import S256Point

# Specify the a and b of the curve y^2 = x^3 + a*x + b
A = 0
B = 7
# Specify the prime of the finite field, p
P = 2**256 - 2**32 - 977
# Specify the x and y coordinates of the generator point G
G = S256Point(
    0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798,
    0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8)
# Specify the order of the group generated by G, n
N = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
